package ru.Kuzevanov_Alexander.NauJava.data.models;

import jakarta.persistence.*;

import java.util.List;

/**
 * Represents a user in the system.  Each instance corresponds to a row in the `users` database table.
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for the user.  Auto-generated by the database.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * The user's username.  Used for login.
     */
    @Column
    private String username;

    /**
     * The user's password.  Should be stored securely (e.g., hashed).
     */
    @Column
    private String password;

    /**
     * A list of roles assigned to the user.  Defines the user's permissions.
     */
    @Column
    private List<String> roles;

    /**
     * The ID of the group the user belongs to.
     */
    @Column
    private Integer groupId;


    /**
     * Returns the unique identifier of the user.
     * @return The user's ID.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the user.  Generally, this should not be set manually; it's managed by the database.
     * @param id The ID to set.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the username of the user.
     * @return The user's username.
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username of the user.
     * @param username The username to set.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns the password of the user.  Be mindful of security implications when accessing this directly.
     * @return The user's password.
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password of the user.  Remember to hash the password before storing it for security.
     * @param password The password to set.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns a list of roles assigned to the user.
     * @return The list of roles.
     */
    public List<String> getRoles() {
        return roles;
    }

    /**
     * Sets the list of roles assigned to the user.
     * @param roles The list of roles to set.
     */
    public void setRoles(List<String> roles) {
        this.roles = roles;
    }

    /**
     * Returns the ID of the group the user belongs to.
     * @return The group ID.
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * Sets the ID of the group the user belongs to.
     * @param groupId The group ID to set.
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}
